name: IOnline
version: 1.1
main: ru.xAveR.IOnline.IOnlineMain
commands:
  ibusy:
      description: Mode not bother
  iinvisible:
      description: Mode invisible
permissions:
    ionline.use:
        default: true
    ionline.ibusy:
        default: true
    ionline.iinvisible:
        default: true